# Generated by Django 5.1.1 on 2024-09-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
