# Generated by Django 5.1.1 on 2024-09-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_client_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='quotation',
            new_name='budget',
        ),
    ]
