# Generated by Django 5.1.1 on 2024-09-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_rename_quotation_material_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(choices=[('materials', 'With Materials'), ('services', 'Service Only')], default='materials', max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='budgets.budget')),
            ],
        ),
    ]
