# Generated by Django 5.1.1 on 2024-09-13 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_budget_budget_type_alter_budget_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='budget',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='total_materials',
            new_name='total_items',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='budget_type',
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.budget')),
            ],
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
