# Generated by Django 5.1.1 on 2024-10-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_remove_service_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='description',
            field=models.TextField(),
        ),
    ]
